### ISSUE TITLE
Some questions about the benchmark result？

### ISSUE THREAD

**Issue by MinboWang** [foolwood/benchmark_results#1]
For nearly a year，I have done some researchs and improvements about challenges on tracking，and I‘m lucky to find your benchmark result about so many state-of-the-art tracker. I was aware that your experiments about the tracker-SRDCFdecon，which paper has done many things about the adaptive learning rate that could fix the problem in quick changes and abrupt occlusion in scenes, but I can't find the source code (the homepage just says it will be comming so), and I am afraid that I have misunderstand the author's mind. So, I wanna know how to get the source code.
Many thanks.

**Comment by foolwood** [comment]
I think you should connect with the author(@Martin Danelljan)[martin.danelljan@liu.se]
He is a famous and distinguished researcher in visual tracking.(DSST SRDCF DeepSRDCF C-COT)
I think he would gladly share his source code with you.

**Comment by MinboWang** [comment]
ok, thx. 
Is this benchmark done by yourself or come from some paper ? Because I have tested the tracker - LCT recently, the experiment result is not so good cause the threshold is not unified in different sequences.

**Comment by foolwood** [comment]
@MinboWang I tested most of the algorithms. To be honest, LCT is a really good choice for engineering. The redetection moduler is really stable in practice. I think the result is reliable .

The difference comes from two parts(campare with the original paper):
* The redetection moduler changed by a SVM classifier.
* The (Precision plots of OPE) in the fig5 may set`` rankingType`` to 'AUC', KCF only gets OPE Precision[0.673].


I don't understand what's the means of "the threshold is not unified in different sequences."

The only changed parameters is function ``search_window.m``. I think it obey the OTB rule.

> It is allowed for a tracker to automatically adapt its parameters only using features from input images.

**Comment by MinboWang** [comment]
What I mean is that the max response threshold can't distinguish quick changes and heavy occlusion. As we all know, the former need high learning rate while the latter need a lowest. That can be tested by a simple experiment but not some statistical data.  I have done much work to verify this. 
I did make the experiment by a SVM classifier, but I think it is not the main reason.
The paper - SRDCFdecon has gave a detailed analysis about above information.

**Comment by foolwood** [comment]
@MinboWang 直接用中文回复了。
1、响应值和表观变化具有很强的相关，但如你所说不是绝对的，无法区分是遮挡还是快速运动。单纯的阈值虽然不是一个优解，但也是一个无奈之举。所以作者用一个保守更新策略维护一个KCF模板。我自己在工业界进行了相关的实习，也认可在“惰性”模板上的响应一定程度上可以帮助改善遮挡和漂移问题。
2、使用响应去纠正学习，这个不是LCT所声明的贡献，所以我觉得你的第一句评价对它来说并不公平。那么如何利用响应去纠正模型（学习率等）是很有意义的工作，然而我觉得从响应出发本身并不合适，MOSSE的文章我自己有进行复现，PSR没有那么稳定，跟踪相对来说对参数比较敏感，简单粗暴的使用这个观察现象并不能解决跟踪问题。这是一个时序问题，仅靠当前帧的响应来判断是不合理的假设，而这确实是SRDCFdecon的贡献所在。（多阅读几篇Martin Danelljan的文章，我个人对他的评价很高，善于做优化问题）。他给出了一个很好的解答，形式化的解决这个问题。但是，这并不是跟踪问题的唯一解答，最近出现的很多跟踪算法根本不进行更新也可以保证state-of-art的表现。既然你说的遮挡需要降低更新率，或者剔除这种错误样本，而快速运动或者表观变化需要加快更新率，这本身就是需要一个复杂模型的支撑，甚至对于SRDCFdecon也一样无法解决表观快速变换，因为很显然，表观快速变换的时候，如果给予了较大的学习率，那么对于其他样本的损失就会增加，这个学习策略本身也是保守的，这是我自己的看法。
谢谢你的交流。

**Comment by MinboWang** [comment]
谢谢，分析得很详细。如你所说，从时间上来说，后面的样本更重要，从正确性上来说，前面的样本更值得参考，如果有一个强大的特征提取办法，这些问题也就没有讨论的必要了。
“最近出现的很多跟踪算法根本不进行更新也可以保证state-of-art的表现。”指的是？ 抱歉，工程需要，深度学习与CNN特征方面我研究的比较少。

**Comment by MinboWang** [comment]
另，关于重新检测问题，我最近也做了一些尝试，参考staple，在目标被遮挡时使用Color Histogram Model重新检测目标位置，因为可以解决目标在遮挡过程中的defomation问题且运算量很小，效果还可以，与SVM的耗时对比目前还没有测，后面会做实验对比。关于你说的LCT中另外一种重检测方法我也会抽时间做相关实验，因为你是如此肯定，我感觉效果应该是OK的。

**Comment by foolwood** [comment]
@MinboWang 不更新的方法有SINT等，只是学术界的一个新思路。我觉得工程并不适合。
另外重检测我之前就是将LCT改写成了C++做工程了，MUSTer的代码由于被加密了，没法学习。这两篇都是15年的，带了一波重检测的风潮。最近又冷静下来了。总的来说，跟踪领域目前百花齐放，工业界需要的是快速鲁棒的算法，目前还得从KCF派系中寻找，GOTURN也是一个新的尝试，不过需要gpu的支持，也不适合工程（嵌入式系统）。
