### ISSUE TITLE
Real-time yes/no column needed

### ISSUE THREAD

**Issue by bertinetto** [foolwood/benchmark_results#11]
Hei @foolwood great work!
As someon else already said, I warmly recommend to add a real-time (yes/no) column to the table. Writing the precise speed could be a huge hassle because it would mean rerunning all methods on the same machine, but I think that simply checking the reported speed in the paper and reporting yes if it's above, say, 20 fps should be very doable.
Maybe even grouping real-time and non-real-time methods could be visually helpful.

For example, in our works we use very lightweight pipelines and we consider real-time as a constraint.
For this reason, it doesn't make much sense to be compared against state-of-the-art methods which are in the 1fps ballpark.

I can do it and then pull request, I have already collected the data.

Cheers,
Luca

**Comment by cepera-ang** [comment]
@bertinetto Luca, can you share the data you collected? Even if @foolwood won't accept the pull request we may fork this repo and add this column anyway (I see it as very important info for many practitioners). Thanks.

**Comment by foolwood** [comment]
I'm a bug fan of Luca.

BTW
I will accept any reasonable pull requests.  :-)

**Comment by cepera-ang** [comment]
Great to hear that :) I hope @bertinetto hasn't lost his desire to share information about FPS of trackers since January, it will be very valuable info here

**Comment by bertinetto** [comment]
It seems that the speed column has been added already :)
Thanks!
