### ISSUE TITLE
KCF OTB2013 result  in Baidu Yun is different from the result in the github?

### ISSUE THREAD

**Issue by bigloong** [foolwood/benchmark_results#13]

**Comment by foolwood** [comment]
I have made an update file and test the results.

Ps. the table results may may be  inconsistent with fig. I will fix it when I have enough time.

**Comment by bigloong** [comment]
Can you email the new KCF OTB2013 result to me ?  my email is 349894542@qq.com

**Comment by foolwood** [comment]
[Baidu Yun](https://pan.baidu.com/s/1c27e9Ew)
