### ISSUE TITLE
Misleading dataset name for the result picture

### ISSUE THREAD

**Issue by chkap** [foolwood/benchmark_results#2]
It seems that the result shown in the provided result picture is not conducted on OTB-50.

I have tested some of the provided results of the mentioned trackers on OTB-50. However, the results of my testing are inconsistent with the results. And I futher plot the results on CVPR13. The results are exactly the same as the provided result picture. So I believe that the dataset name for the result picture is wrong.

**Comment by foolwood** [comment]
You are right. I plot the results on CVPR13. I will change the title.
Thank you for pointing out the mistake.
 And I will withdraw some uncertain information about the benchmark.
