### ISSUE TITLE
FCNT link is lost

### ISSUE THREAD

**Issue by DoubleKing0625** [foolwood/benchmark_results#21]
I think the link for FCNT paper is lost. Anyone can give a available link?

**Comment by foolwood** [comment]
The link is 
http://www.cv-foundation.org/openaccess/content_iccv_2015/papers/Wang_Visual_Tracking_With_ICCV_2015_paper.pdf


I will check the list, and relink to the more stable links.

**Comment by DoubleKing0625** [comment]
Thanks a lot
