### ISSUE TITLE
 the initial tracking object window? 

### ISSUE THREAD

**Issue by so-as** [foolwood/benchmark_results#22]
Hi, do all these track algorithms need  the pre-detection to give the initial tracking object window? or the tracker can find the first tracking window by itself? thx @foolwood @flyers @longcw @HakaseH

**Comment by flyers** [comment]
The initial object bounding box must be given to the tracker.

**Comment by so-as** [comment]
@flyers yeah, It seems the tracker is tracking by the initialization of  the detection window .  I hope there will be some algorithms to just do tracking.  Thx
