### ISSUE TITLE
the converting formula between EFO  and fps ? 

### ISSUE THREAD

**Issue by so-as** [foolwood/benchmark_results#23]
I am curious with the the converting formula between EFO  and fps in  the papers , anyone can tell me? @flyers @longcw @foolwood @HakaseH

**Comment by foolwood** [comment]
Please do not open new issues with these problem, you can get help from reading paper!
Or
You can  join the QQ group (**261539583**) .

**Comment by foolwood** [comment]
In VOT2016 paper, the authors think **20 EFO** is the criterion for **real-time tracking**. 

But in practice, I found that trackers **with more than 10 EFO** has a good real-time performance.

**Comment by so-as** [comment]
thank you very much@foolwood
