### ISSUE TITLE
What's the meaning of the thunder in the tree graph?

### ISSUE THREAD

**Issue by NinetailsBear9** [foolwood/benchmark_results#27]
The fireworks should mean "VOT", but the meaning of thunder is ?
add some legends?

**Comment by foolwood** [comment]
Sorry for the ambiguous expression. I will fix the problem. Thanks.

The thunder :zap:  means **VOT realtime experiment** 

The :tada: symbol means **VOT baseline experiment**

**Comment by yl1991** [comment]
How about the digits? What do they mean? for example ECO has 🎉  ⚡️ 3, what does 3 mean?

**Comment by foolwood** [comment]
@yl1991 
 ECO get the 3rd in the baseline experiment.
 ECO_hc get the 3rd in the realtime experiment.
I don't want to list this two separately.
