### ISSUE TITLE
Could you please give me a result about KCF on OTB_CVPR13

### ISSUE THREAD

**Issue by zhuangjunfei** [foolwood/benchmark_results#30]
I am trying to reproduce the KCF result on OTB_CVPR13, but there always be some mistakes, the precision only reach 0.622 and the success 0.483. I want to compare with your KCF result, so I could find the mistake.
my mailbox is 627889533@qq.com. Thanks!

**Comment by foolwood** [comment]
You can find result files in [BaiduYun](https://pan.baidu.com/s/1c27e9Ew#list/path=%2F).
