### ISSUE TITLE
Adding another competitive tracker?

### ISSUE THREAD

**Issue by tfwu** [foolwood/benchmark_results#31]
Dear Qiang, 

Thank you very much for this great benchmark results. 

FYI: We also had a tracker, AOGTracker (https://github.com/tfwu/RGM-AOGTracker, project page: http://www4.ncsu.edu/~twu19/project_posts/AOGTracker/), which was tested on TB100/50/2013, VOT13/14/15 with competitive results obtained.  

Thank you very much

**Comment by foolwood** [comment]
Thank you for providing such good paper.

I feel ashamed to have little attention on TPAMI, TIP...

I will read this paper and update performance table later.
