### ISSUE TITLE
which DCF in the figure? 

### ISSUE THREAD

**Issue by wjtan99** [foolwood/benchmark_results#37]
Hi,  in the figure, there is a DCF to achieve >200 FPS.  Which DCF is this, can you point me to the github or the author's project page? 
Thanks.

**Comment by foolwood** [comment]
DCF was proposed in [KCF](https://arxiv.org/pdf/1404.7584.pdf).

> We also propose a fast multi-channel extension of linear correlation filters, via a linear kernel, which we call Dual Correlation Filter (DCF).

From 
High-Speed Tracking with Kernelized Correlation Filters.
