### ISSUE TITLE
Success Plots and precision plot 

### ISSUE THREAD

**Issue by MSathishkumar1990** [foolwood/benchmark_results#46]
I need to use OTB benchmark for comparing trackers with success and precision rates.  For that, I m using **tracker_benchmark_v1.0** downloaded from 
https://sites.google.com/site/trackerbenchmark/benchmarks/v10.

Initially, I tried to get the performance plot for a tracker(KCF). I faced many issues during program execution. Please help me to solve these issues. 

Thanks in advance...

**Comment by foolwood** [comment]
Sorry for that, it's far beyond this repository.

You can search for a tutorial from google.
