### ISSUE TITLE
Difference instanceSize when training and testing

### ISSUE THREAD

**Issue by zhangliliang** [foolwood/benchmark_results#5]
Hi. Thanks for sharing such a good code for studying.

I have a problem when reading your code.

In the testing procedure, the instanceSize set to 255. However, during the training time the instanceSize is set to 255 - 2*8.

Why they are different? And what is the meaning of subtracting 2*8 during the training time?

Wait for your response.

**Comment by foolwood** [comment]
?????

**Comment by zhangliliang** [comment]
Oh, sorry.

I mix this repo with another repo.
