### ISSUE TITLE
Which paper does the algorithm with the _CA suffix in the chart name come from?

### ISSUE THREAD

**Issue by TCBocean** [foolwood/benchmark_results#53]
I saw some algorithms with the name _CA suffix in the "OTB2013 Precision plots of OPE" chart. Which paper does the algorithm with the _CA suffix in the chart name come from?
Looking forward to your answer.

**Comment by foolwood** [comment]
CACF: Matthias Mueller, Neil Smith, Bernard Ghanem. "Context-Aware Correlation Filter Tracking." CVPR (2017 oral)

**Comment by TCBocean** [comment]
I appreciate it!
