### ISSUE TITLE
A new interesting paper to add to your list

### ISSUE THREAD

**Issue by JonathonLuiten** [foolwood/benchmark_results#64]
Our recent ArXiv submission I think would make an interesting addition to your list.

It obtains current best result on 11 different tracking benchmarks.

https://arxiv.org/abs/1911.12836

Thanks for making this list! It is a super useful resource!

Regards,
Jonathon

**Comment by Dawn5786** [comment]
Would you help me where can I find the official implementation code of your rencent SiamR-CNN tracker?

**Comment by Dawn5786** [comment]
> Our recent ArXiv submission I think would make an interesting addition to your list.
> 
> It obtains current best result on 11 different tracking benchmarks.
> 
> https://arxiv.org/abs/1911.12836
> 
> Thanks for making this list! It is a super useful resource!
> 
> Regards,
> Jonathon

Would you help me where can I find the official implementation code of your rencent SiamR-CNN tracker?

**Comment by JonathonLuiten** [comment]
Hey! We plan on releasing the source code at some point in the near future, but it won't be for at least a month.

**Comment by foolwood** [comment]
@JonathonLuiten  Will update this week.
