### ISSUE TITLE
why the results of CVPR2013 and TB50 are different?

### ISSUE THREAD

**Issue by zhengzhugithub** [foolwood/benchmark_results#9]
why the results of CVPR2013 and TB50 are different?

**Comment by foolwood** [comment]
CVPR2013 refers to the dataset reported in "[Online Object Tracking: A Benchmark](http://faculty.ucmerced.edu/mhyang/papers/cvpr13_benchmark.pdf)." CVPR (2013).
The CVPR2013 dataset contains 50 videos and 51 targets.

TB50 and TB100 are proposed in "[Object Tracking Benchmark](http://ieeexplore.ieee.org/document/7001050/)" TPAMI (2015).


Many authors might be  confused with CVPR2013 and TB50, but I think the two datasets are not the same. 

>The scores from the TB-50 dataset are lower than those from the TB-100 set as the TB-50 set consists of more challenging sequences

If you want to know more details, please read the two articles.

**Comment by zhengzhugithub** [comment]
thank you

**Comment by zhengzhugithub** [comment]
thank you
